<a href="https://colab.research.google.com/github/kwanda2426/projects/blob/main/geospatial/HW_4/Week04_Interpolation_Kriging_Kwanda_1077167.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Import libraries**

In [ ]:
!pip install -q geostatspy statsmodels geostatsmodels numba

In [6]:
import os                                                     # for file and directory operations
import numpy as np                                            # for numerical operations and ndarrays
import pandas as pd                                           # for handling data in DataFrame format
import matplotlib.pyplot as plt                               # for plotting and visualization
from statsmodels.stats.weightstats import DescrStatsW         # for weighted statistics calculations
from scipy.optimize import curve_fit                          # for curve fitting
import geostatspy.GSLIB as GSLIB                              # GSLIB utilities, visualization, and wrapper functions
import geostatspy.geostats as geostats                        # GSLIB methods converted to Python
import geostatspy                                             # for accessing the package version and general utilities


from tqdm import tqdm                                         # progress bar for loops
from functools import partialmethod                           # used to modify tqdm to suppress the status bar
tqdm.__init__ = partialmethod(tqdm.__init__, disable=True)    # suppress the status bar for tqdm

from matplotlib.ticker import (MultipleLocator, AutoMinorLocator) # control over axes ticks in plots
plt.rc('axes', axisbelow=True)                                # ensure grid lines are plotted below plot elements

import scipy.spatial as sp                                    # for spatial data structures and algorithms (KDTree)
import geopandas as gpd                                       # for handling geospatial data (GeoDataFrame)
from matplotlib import gridspec                               # custom subplots

# Define ignore_warnings before using it
ignore_warnings = True                                        # flag to ignore warnings

# Check and apply the warning filter
if ignore_warnings == True:
    import warnings
    warnings.filterwarnings('ignore')

from IPython.utils import io                                  # mute output from simulation

cmap = "Spectral_r"                                           # color map

# **Functions**

In [ ]:
from matplotlib.ticker import (MultipleLocator, AutoMinorLocator) # control of axes ticks

def add_grid():
    ax = plt.gca()
    ax.grid(True, which='major', linewidth=1.0, alpha=0.7)
    ax.grid(True, which='minor', linewidth=0.5, linestyle='--', alpha=0.4)
    ax.tick_params(which='major', length=7)
    ax.tick_params(which='minor', length=4)
    ax.xaxis.set_minor_locator(AutoMinorLocator())
    ax.yaxis.set_minor_locator(AutoMinorLocator())

# **1. Data & Week 3 Foundations**

### 1.1 Load Data

In [ ]:
# Load data from Github
url = "https://raw.githubusercontent.com/kwanda2426/projects/main/geospatial/HW_4/CuMineBH.csv"
df = pd.read_csv(url)
df.head()

         EAST       NORTH     Cu
0   56.122424  105.841818  0.750
1   74.176970   81.483939  0.664
2  140.032424  191.491515  0.202
3  158.912121  133.599697  0.408
4   50.455455  211.942121  0.602

In [7]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
EAST,1575.0,255.912312,158.598035,0.000,119.457424,237.761515,401.520303,561.063636
NORTH,1575.0,155.871652,63.364120,0.000,113.178939,163.326061,207.209848,268.143939
Cu,1575.0,0.405832,0.230091,0.026,0.244000,0.356000,0.522000,1.968000

### 1.2 Declustering recap

### 1.3 Normal score transform (NST) recap

### 1.4 Variogram recap & model selection

# **2. Interpolation Grid & Search Strategy**

# **3. IDW Interpolation (p = 1, 2, 3, 4, 5)**

### 3.1 Method

### 3.2 Maps

### 3.3 Observation summary

# **4. Simple Kriging (SK)**

### 4.1 Assumptions & setup

### 4.2 Estimation

### 4.3 Maps

# **5. Ordinary Kriging (OK)**

### 5.1 Assumptions & setup

### 5.2 Estimation

### 5.3 Maps

# **6. For each method, compute Validation & Comparative Analysis**

# **7. Observations and Conclusion**